#!/usr/bin/env php
<?php
/**
 * This file is part of the Phalcon Kit.
 *
 * (c) Phalcon Kit team
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

use App\Bootstrap;

$loader = require 'loader.php';
echo new Bootstrap('cli')->run();
